name: check

on:
  schedule:
    # 7AM EST (11AM UTC) Mon-Fri
    - cron: "0 11 * * 1-5"
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 15
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        version: ["1.22", "1.23"]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: ${{ matrix.version }}
          cache: true

      - name: build
        run: go build ./...

      - name: run tests and benchmarks
        run: go test -race -bench=. -benchtime=1x ./...

  test-success:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 1
    steps:
      - name: check test matrix status
        if: ${{ needs.test.result != 'success' }}
        run: exit 1
